config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get 'page/:page' => 'home#index'

  get 'login' => 'session#new', as: :login
  get 'logout' => 'session#destroy', as: :logout
  post 'login' => 'session#create'

  get 'register' => 'user#new', as: :register
  post 'register' => 'user#create'

  get 'update' => 'post#new', as: :new_post
  post 'update' => 'post#create', as: :posts

  get 'settings' => 'user#edit', as: :settings
  post 'settings' => 'user#update'

  get 'u/:username' => 'user#show', as: :user
  get 'u/:username/following' => 'user#following', as: :user_following
  get 'u/:username/followed_by' => 'user#followed_by', as: :user_followed_by
  get 'u/:username/follow' => 'user#follow', as: :user_follow
  get 'u/:username/unfollow' => 'user#unfollow', as: :user_unfollow

  get 'u/:username/post/:post_id' => 'post#show', as: :post
  get 'u/:username/post/:post_id/like' => 'post#like', as: :like_post
  get 'u/:username/post/:post_id/unlike' => 'post#unlike', as: :unlike_post
  get 'u/:username/post/:post_id/delete' => 'post#destroy', as: :destroy_post

end

app/models/follow.rb
class Follow < ActiveRecord::Base
	belongs_to :user
	has_one :following, :class_name => 'User'
end

app/models/like.rb
class Like < ActiveRecord::Base
	belongs_to :user
	belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base

	validates :content, presence: true
	validates :user_id, presence: true

	belongs_to :user
	has_many :likes
	has_many :reposts
end

app/models/repost.rb
class Repost < ActiveRecord::Base
	belongs_to :user
	belongs_to :post
end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base
	include BCrypt

	validates :username, presence: true
	validates :username, uniqueness: true
	validates :display_name, presence: true
	validates :email, presence: true
	validates :email, uniqueness: true
	validates :username, format: { with: /[a-zA-Z0-9_]+/, message: "Only allows letters, numbers, and underscores" }

	has_many :posts
	has_many :likes
	has_many :reposts
	has_many :follows

	def password
		@password ||= Password.new(password_digest)
	end

	def password=(new_password)
		@password = Password.create(new_password)
		self.password_digest = @password
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		if session[:user].present?
			@user = User.find(session[:user])
			@posts = Post.where(user_id: @user.follows.collect {|x| x.following_id }.push(session[:user])).order(created_at: :desc)
		else
			redirect_to :login
		end
	end
end

app/controllers/post_controller.rb
class PostController < ApplicationController
	def show
		@post = Post.find(params[:id])
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		if @post.save!
			flash[:success] = "Update posted!"
			redirect_to :root
		else
			flash[:error] = "There was an error posting your update."
			redirect_to :new_post_path
		end
	end

	def destroy
		@post = Post.find(params[:post_id])
		Post.delete(@post.id)
		redirect_to :root
	end

	def like
		@like = Like.new(post_id: params[:post_id], user_id: session[:user])
		@like.save!
		redirect_to user_path(params[:username])
	end

	def unlike
		@like = Like.find_by_post_id_and_user_id(params[:post_id], session[:user])
		Like.delete(@like.id)
		redirect_to user_path(params[:username])
	end

	private

	def post_params
		params.require(:post).permit(:content, :user_id, :id)
	end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
	def new

	end

	def create
		@user = User.find_by_username(params[:user][:username])
		if @user && @user.password == params[:user][:password]
			flash[:success] = "You've been successfully logged in."
			session[:user] = @user.id
			redirect_to :root
		else
			flash[:error] = "Your username or password was incorrect."
			redirect_to :login
		end
	end

	def destroy
		session[:user] = nil
		flash[:success] = "You've been logged out."
		redirect_to :login
	end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		@user.password = params[:user][:password]
		if @user.save!
			session[:user] = @user.id
			redirect_to :root
		else
			redirect_to :register_path
		end
	end

	def show
		@user = User.find_by_username(params[:username])
		if session[:user]
			@current_user = User.find(session[:user])
			if @current_user.present? && @current_user.follows.collect {|x| x.following_id }.include?(@current_user.id)
				@following_user = true
			else
				@following_user = false
			end
		end
		@posts = Post.where(user_id: @user.id).order(created_at: :desc)
	end

	def edit
		if (session[:user].nil?)
			redirect_to login_path
		end
		@user = User.find(session[:user])
	end

	def update
		@user = User.find(session[:user])
		if @user.update_attributes!(user_params)
			flash[:success] = "Your settings were updated."
		else
			flash[:error] = "There was an error updating your settings."
		end
		redirect_to settings_path
	end

	def following
		@user = User.find_by_username(params[:username])
		@follows = Follow.where(user_id: @user.id)
		@followed_users = User.find(@follows.collect{|x| x.following_id})
	end

	def followed_by
		@user = User.find_by_username(params[:username])
		@follows = Follow.where(following_id: @user.id)
		@followers = User.find(@follows.collect {|x| x.user_id})
	end

	def follow
		@user = User.find_by_username(params[:username])
		@follow = Follow.new(user_id: session[:user], following_id: @user.id)
		@follow.save!
		redirect_to user_path(@user.username)
	end

	def unfollow
		@user = User.find_by_username(params[:username])
		@follow = Follow.where(user_id: session[:user], following_id: @user.id)
		Follow.delete(@follow.id)
		redirect_to user_path(@user.username)
	end

	private

	def user_params
		params.require(:user).permit(:id, :username, :display_name, :password_digest, :password, :email)
	end
end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
  	if session[:user].present?
  		@user = User.find(session[:user])
  	else
  		nil
  	end
  end

  def is_logged_in?
  	if session[:user].present?
  		true
  	else
  		false
  	end
  end

  def current_user_likes_post?(id)
    if is_logged_in?
      @user = User.find(session[:user])
      @liked_posts = @user.likes.collect {|x| x.post_id }
      if @liked_posts.include?(id)
        true
      else
        false
      end
    else
      false
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/home/index.erb
<div class="col-md-8 col-md-offset-2">
	<h1>Your Feed</h1>

	<% @posts.each do |post| %>
		<%= render partial: 'shared/post', locals: {post: post} %>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>TXT</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
	<nav class="navbar navbar-default">
	  <div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="/"><i class="glyphicon glyphicon-pencil"></i> TXT</a>
	    </div>

	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav navbar-right">
	      	<% if session[:user] %>
	        <li><%= link_to "Post", new_post_path %></li>
	        <% end %>
	        <li class="dropdown">
	          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="glyphicon glyphicon-user"></i> <span class="caret"></span></a>
	          <ul class="dropdown-menu">
	          	<% if session[:user] %>
	            <li><%= link_to "View Profile", user_path(current_user.username) %></li>
	            <li><%= link_to "Account Settings", settings_path %></li>
	            <li role="separator" class="divider"></li>
	            <li><%= link_to "Log Out", logout_path %></li>
	            <% else %>
	            <li><%= link_to "Log In", login_path %></li>
	            <% end %>
	          </ul>
	        </li>
	      </ul>
	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>
	<div class="container">
		<% if flash[:success] %>
			<div class="alert alert-success" role="alert">
				<%= flash[:success] %>
			</div>
		<% end %>

		<% if flash[:error] %>
			<div class="alert alert-danger" role="alert">
				<%= flash[:error] %>
			</div>
		<% end %>
		<%= yield %>
	</div>
</body>
</html>

app/views/post/new.erb
<div class="col-md-6 col-md-offset-3">
	<h1>New Update</h1>
	<%= form_for @post, url: {action: "create"} do |f| %>
		<div class="form-group">
			<%= f.text_area :content, class: 'form-control' %>
		</div>
		<div class="form-group">
			<%= f.hidden_field :user_id, value: session[:user] %>
			<%= f.button "Post", type: 'submit', class: 'btn btn-primary' %>
		</div>
	<% end %>
</div>

app/views/post/show.erb
<div class="col-md-6 col-md-offset-3">
	<%= render partial: 'shared/post', locals: {post: @post} %>
</div>

app/views/session/new.erb
<div class="col-md-6 col-md-offset-3">
	<h2>Log In <span class="label label-link"><%= link_to "Or register", register_path %></span></h2>

	<%= form_for :user do |f| %>
		<div class="form-group">
			<%= f.label :username %>
			<%= f.text_field :username, class: 'form-control' %>
		</div>
		<div class="form-group">
			<%= f.label :password %>
			<%= f.password_field :password, class: 'form-control' %>
		</div>
		<div class="form-group">
			<%= f.button "Log In", type: 'submit', class: 'btn btn-primary' %>
		</div>
	<% end %>
</div>

app/views/shared/_post.erb
<div class="post">
	<div class="post-header">
		<div class="post-author">
			<span class="displayname"><%= post.user.display_name %></span> <%= link_to "@#{post.user.username}", user_path(post.user.username), class: 'userlink' %>
		</div>
		<div class="post-date">
			<%= time_ago_in_words(post.created_at) %> ago
		</div>
	</div>
	<div class="post-content">
		<%= post.content %>
	</div>
	<div class="post-footer">
		<div class="post-likes">
			<b>Likes:</b> <%= post.likes.length %> <% if session[:user].present? && !current_user_likes_post?(post.id) %><%= link_to "Like?", like_post_path(username: post.user.username, post_id: post.id), class: 'btn btn-xs btn-primary likebtn' %><% elsif session[:user].present? && current_user_likes_post?(post.id) %><%= link_to "Unlike?", unlike_post_path(username: post.user.username, post_id: post.id), class: 'btn btn-xs btn-primary unlikebtn' %><% end %>
 		</div>
		<div class="post-management">
			<% if post.user.id == session[:user] %>
			<%= link_to "Delete", destroy_post_path(username: post.user.username, post_id: post.id), class: 'btn btn-xs btn-danger' %>
			<% end %>
		</div>
	</div>
</div>

app/views/user/edit.erb
<div class="col-md-6 col-md-offset-3">
	<h1>Account Settings</h1>
	<%= form_for @user, url: {action: 'update'}, method: 'post' do |f| %>
		<div class="form-group">
			<%= f.label :display_name %>
			<%= f.text_field :display_name, class: 'form-control' %>
		</div>
		<div class="form-group">
			<%= f.label :password, "New Password" %>
			<%= f.password_field :password, class: 'form-control' %>
		</div>
		<div class="form-group">
			<%= f.button "Update Settings", type: 'submit', class: 'btn btn-primary' %>
		</div>
	<% end %>
</div>

app/views/user/followed_by.erb
<div class="col-md-8 col-md-offset-2">
	<h2>Following @<%= @user.username %></h2>
	<ul>
	<% @followers.each do |follower| %>
		<li><strong><%= follower.display_name %></strong> <%= link_to "@#{follower.username}", user_path(follower.username) %></li>
	<% end %>
	</ul>
</div>

app/views/user/following.erb
<div class="col-md-8 col-md-offset-2">
	<%= link_to "< Back to Profile", user_path(@user.username) %>
	<h2>@<%= @user.username %> Follows</h2>
	<ul>
	<% @followed_users.each do |following| %>
		<li><strong><%= following.display_name %></strong> <%= link_to "@#{following.username}", user_path(following.username) %></li>
	<% end %>
	</ul>
</div>

app/views/user/new.erb
<div class="col-md-6 col-md-offset-3">
	<h2>Sign Up <span class="label label-link"><%= link_to "Or log In", login_path %></h2>

	<%= form_for :user do |f| %>
		<div class="form-group">
			<%= f.label :username %>
			<%= f.text_field :username, class: 'form-control' %>
		</div>
		<div class="form-group">
			<%= f.label :display_name %>
			<%= f.text_field :display_name, class: 'form-control' %>
		</div>
		<div class="form-group">
			<%= f.label :email %>
			<%= f.email_field :email, class: 'form-control' %>
		</div>
		<div class="form-group">
			<%= f.label :password %>
			<%= f.password_field :password, class: 'form-control' %>
		</div>
		<div class="form-group">
			<%= button_tag 'Sign Up', type: 'submit', class: 'btn btn-primary' %>
		</div>
	<% end %>
</div>

app/views/user/show.erb
<div class="col-md-8 col-md-offset-2">
	<h2><%= @user.display_name %> <span class="label label-default">@<%= @user.username %></span></h2>
	<p><%= link_to "Follows", user_following_path(@user.username) %> &bull; <%= link_to "Followed By", user_followed_by_path(@user.username) %><% if session[:user].present? && !@following_user %> &bull; <%= link_to "Follow", user_follow_path(@user.username), class: 'btn btn-primary btn-xs' %><% elsif session[:user].present? && @following_user %> &bull; <%= link_to "Unfollow", user_unfollow_path(@user.username), class: 'btn btn-primary btn-xs' %><% end %></p>
	<% @posts.each do |post| %>
		<%= render partial: 'shared/post', locals: {post: post} %>
	<% end %>
</div>